version: "3.5"

services:

  django:
    build: ./
    ports:
      - 8000:8000
    container_name: test-blog-api
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    restart: always

volumes:
  static:
  media:
